# Generated by Django 4.2.23 on 2025-08-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
