# Generated by Django 4.2.23 on 2025-08-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='engine_size',
        ),
        migrations.AddField(
            model_name='post',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
